interval_s = 10
batchsize = 100
description = "keeping track of your infra status"

[service.moonlit]
endpoint = "https://moonlit.technology"

[service.site]
endpoint = "https://alemi.dev"

[service."code.mp"]
endpoint = "https://code.mp"

[service.down]
endpoint = "https://down.alemi.dev"
